-- Выполни этот SQL в Supabase -> SQL Editor.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  user_name text not null check (char_length(user_name) between 1 and 24),
  text text not null check (char_length(text) between 1 and 4000),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

grant select, insert on public.messages to authenticated;

create policy "Authenticated users can read messages"
on public.messages for select
to authenticated
using (true);

create policy "Users can send as themselves"
on public.messages for insert
to authenticated
with check ((select auth.uid()) = user_id);

create index if not exists messages_created_at_idx on public.messages(created_at);

-- Включаем realtime для таблицы сообщений.
alter publication supabase_realtime add table public.messages;
